# Generated by Django 4.2.7 on 2024-01-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_result_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='IDParticipant',
            new_name='IDParticipants',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='IDparticipants',
            new_name='IDParticipants',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='fair_share',
            new_name='fairShare',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='item',
            new_name='itemWon',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='total_value',
            new_name='totalValue',
        ),
    ]
